 <!-- ARCHIVES JS -->
 <script src="{{ asset('frontend/findhouse/js/jquery-3.5.1.min.js') }}"></script>
 <script src="{{ asset('frontend/findhouse/js/tether.min.js') }}"></script>
 <script src="{{ asset('frontend/findhouse/js/popper.min.js') }}"></script>
 <script src="{{ asset('frontend/findhouse/js/bootstrap.min.js') }}"></script>
 <script src="{{ asset('frontend/findhouse/js/mmenu.min.js') }}"></script>
 <script src="{{ asset('frontend/findhouse/js/mmenu.js') }}"></script>
 <script src="{{ asset('frontend/findhouse/js/smooth-scroll.min.js') }}"></script>
 <script src="{{ asset('frontend/findhouse/js/ajaxchimp.min.js') }}"></script>
 <script src="{{ asset('frontend/findhouse/js/newsletter.js') }}"></script>
 <script src="{{ asset('frontend/findhouse/js/color-switcher.js') }}"></script>
 <script src="{{ asset('frontend/findhouse/js/inner.js') }}"></script>
